### ISSUE TITLE
Build a prototype

### ISSUE THREAD

**Issue by Zambumon** [Zambumon/Lubrigante#1]

**Comment by Zambumon** [comment]
Ordered a 4 layer 5mm half plate from sculpteo.

**Comment by adbX** [comment]
I have a `1/2 inch, 2 x 1/4 inch and 1/8 inch (12.7, 6.35 and 3.175 mm)` acrylic plates on hand and also have a laser cutting machine ready to go. Other than the screw lengths, would there be any issues?

**Comment by Zambumon** [comment]
I've received the case. And I'm currently writing a short document with all the tweaks needed.

**Comment by DanielGGordon** [comment]
@Zambumon I'm interested in producing at least 25x of these now that a PCB GB is open.

**Comment by Zambumon** [comment]
@DanielGGordon this issue hasn't been closed. The case need some small tweaks and that PCB you are talking about isn't Maarten's. I strongly suggest you to hold your horses. 

If you decide to sell them at your store, remember to follow the license on this repository.

**Comment by airyimbin** [comment]
Wait if that preorder for the PCB isn't the one designed by Maarten, then what PCB is it?
I'm kind of confused since the GB link doesn't work.

**Comment by Maartenwut** [comment]
> Wait if that preorder for the PCB isn't the one designed by Maarten, then what PCB is it?
> I'm kind of confused since the GB link doesn't work.

I don't know who will design this one, but it certainly isn't me. I quit the project. The GB link doesn't work because the moderators at geekhack have to approve every GB thread and they have not done that yet.

**Comment by airyimbin** [comment]
So the picture he posted of the PCB was just your initial prototype? 
At the end of the day as long it works I guess I'm ok with it.

**Comment by Maartenwut** [comment]
> 
> 
> So the picture he posted of the PCB was just your initial prototype?
> At the end of the day as long it works I guess I'm ok with it.

The picture of the PCB with the routing is my finished design. Because I quit the project he is not allowed to use it anymore.

**Comment by airyimbin** [comment]
Thanks for clarifying.

**Comment by Zambumon** [comment]
Known issues with the prototype case:
- Switch holes should be a little bit tighter due to kerf. Reducing them could be an option. I bypassed this problem by placing some electrical tape aound the switch and they holds the switch down perfectly.
- Cone feet screw holes should be M4, not M3. For the prototype case, I just end up superglueing them.
- Due to the nature of acrylic, some people might want to add 3rd cone feet right in the middle to avoid the flex. 
- Screw holes could be slightly thighter if we want to use the bottom piece to screw them. I just used some masking tape around each of the screws and there was no need for anything else.

The case doesn't present any major issues and it is compatible with the original PCB.

**Comment by wamsleymj** [comment]
I would love to help contribute, please let me know how I can assist.

Couple of things in the read me that I think could use clarification.

When importing the files, make sure to set the scale to millimetres.
Are you speaking about importing the .dxf file into an AutoCAD like program or a fabrication website?

Ideally you'd want to use 20+ screws and some nuts.
So instead of 8 screws, there should be 20 around the case? Can the case handle that? Are you going to add the holes to the files, or should we manipulate them to add extra? It looks like the case can only take more screw holes on the top and bottom edges.

I appreciate all the hard work. Really excited about this project.

**Comment by Zambumon** [comment]
> When importing the files, make sure to set the scale to millimetres.
> Are you speaking about importing the .dxf file into an AutoCAD like program or a fabrication website?

Both. Whenever you get asked about the scale, make sure you are using milimiters and double check it.

> Ideally you'd want to use 20+ screws and some nuts.
> So instead of 8 screws, there should be 20 around the case? Can the case handle that? Are you going to add the holes to the files, or should we manipulate them to add extra? It looks like the case can only take more screw holes on the top and bottom edges.

Bad phrasing on my side, it should say "20mm or more"

**Comment by Zambumon** [comment]
Prototype built, files and readme updated.

**Comment by raphaelfaria** [comment]
@Zambumon would the kerf (the loose switches issue) be a problem if I go the 1.5mm metal plate route? Probably not, right?

**Comment by Zambumon** [comment]
@raphaelfaria I don't think so.
