### ISSUE TITLE
Acrylic thicknesses & tolerance

### ISSUE THREAD

**Issue by gwerbin** [Zambumon/Lubrigante#3]
In the USA I think these are the most common acrylic thicknesses you will find (in mm):

- 1.5
- 2.5
- 3
- 4.5
- 6
- 9

Since those are somewhat misaligned with the numbers recommended by Yuktsi it might be useful to have a sense of the alternatives available.

In addition, apparently due to manufacturing tolerance "5mm" acrylic can end up being too thick for switches to sit correctly. So 4.5mm is typically what I have been told to use in the past for plates anyway.

I imagine you can get away with reducing both 5mm layers to 4.5mm and still have the PCB clear the bottom. Then you can do the top piece as two layers (4.5+3) or just leave it as a "mid height" bezel. But it would be good to have your thoughts, maybe once you've received your prototype.

**Comment by Zambumon** [comment]
I'm currently testing 3mm with formulor. 3mm is easier to find and more inexpensive, it shouldn't crack the plate when installing the switches, and you can fit a 6 layer 3mm case within the constrains provided by Formulor (and probably Ponoko).

I'll post the results of my prototyping adventure at #1
