### ISSUE TITLE
Ponoko error - stroke colours

### ISSUE THREAD

**Issue by rwarr** [Zambumon/Lubrigante#5]
I was trying the dxf file for the half plate on Ponoko where it gave out an error regarding about the stroke colour.

> There appears to be a problem with your design file: The stroke colors in your .dxf file aren’t quite right. Cutting strokes need to be RGB (0,0,255) blue. Vector engraving strokes need to be RGB (255,0,0) red.

**Comment by Zambumon** [comment]
Open the file with inkscape or illustrator and change the colors.

**Comment by rwarr** [comment]
Also, seems like ponoko is complaining about stray anchor points.

**Comment by Maartenwut** [comment]
Zambumon is providing the designs, it's up to you to make them fit the manufacturer's specifications.

**Comment by joehenriod** [comment]
@rwarr Did you get your files working? I'm editing some for Ponoko in Illustrator now if you want them posted.

**Comment by addcninblue** [comment]
@joehenriod hey! did you manage to get working files? I'd love to print my own. Also, how much was the total cost?
